# Generated by Django 5.0.6 on 2024-05-18 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_star_average_article_star_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['article', 'user'], name='articles_ra_article_842780_idx'),
        ),
    ]
